spring.application.name=boot-legacy

# default -> 8080
# 주석(비활성)하여 비워두거나 기본값을 호출할 수 있음
#server.port=8080
#server.port=8888
#server.port=${PORT:8081}
server.port=${PORT:8080}

# view resolver 설정
# controller -> string -> (prefix)string(suffix) -> 템플릿 호출
# webapp -> jasper 의존성이 알아서 이 경로를 감지
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp